sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
  - "6"
  - "4"
before_script:
   - ./scripts/start-server.sh
script:
   - make ci
after_success:
   - npm run coveralls
after_script:
   - ./scripts/stop-server.sh
notifications:
  irc: "chat.freenode.net#brass-monkey"
env:
  global:
    - USER: ci
